const quizData = {
    courseTitle: "CCNA IV",
    'Sheet-1': {
        title: "Sheet-1",
        data: [
            { type: 'mcq', q: "1. How many bits are in an IPv4 address?", options: ["16 bits", "32 bits", "64 bits", "128 bits"], correct: 1 },
            { type: 'mcq', q: "2. What does MAC stand for?", options: ["Media Access Control", "Multiple Address Code", "Main Application Channel", "Modular Access Circuit"], correct: 0 },
            { type: 'mcq', q: "3. Which OSI layer is responsible for routing and logical addressing?", options: ["Data Link Layer", "Network Layer", "Transport Layer", "Application Layer"], correct: 1 },
            { type: 'mcq', q: "4. Which protocol provides a reliable connection?", options: ["UDP", "TCP", "ICMP", "FTP"], correct: 1 },
            { type: 'mcq', q: "5. What command shows IP configuration on a Windows computer?", options: ["ping", "ipconfig", "traceroute", "netstat"], correct: 1 },
            { type: 'mcq', q: "6. What is the broadcast address for the network 192.168.1.0?", options: ["192.168.1.1", "192.168.1.254", "192.168.1.255", "192.168.0.255"], correct: 2 },
            { type: 'mcq', q: "7. Which type of route is manually configured by an administrator?", options: ["Direct route", "Static route", "Dynamic route", "Default route"], correct: 1 },
            { type: 'mcq', q: "8. How is a default route represented in IPv4?", options: ["127.0.0.1/8", "0.0.0.0/0", "255.255.255.0/24", "192.168.1.0/24"], correct: 1 },
            { type: 'mcq', q: "9. Which device forwards packets based on a routing table?", options: ["Switch", "Hub", "Router", "Bridge"], correct: 2 }
        ]
    },
    'Sheet-7': {
        title: "Sheet-7 - VPN & IPsec Exam",
        data: [
            { type: 'mcq', q: "1. What does a VPN primarily provide?", options: ["High-speed LAN", "Encrypted private communication", "Wireless connectivity", "Data compression"], correct: 1 },
            { type: 'mcq', q: "2. Which protocol is commonly used for VPN encryption?", options: ["HTTP", "IPsec", "FTP", "SMTP"], correct: 1 },
            { type: 'mcq', q: "3. VPNs help organizations mainly by:", options: ["Increasing hardware costs", "Reducing connectivity costs", "Eliminating the need for routers", "Removing internet dependency"], correct: 1 },
            { type: 'mcq', q: "4. A site-to-site VPN connects:", options: ["Two hosts only", "Mobile users to a server", "Entire networks", "Printers together"], correct: 2 },
            { type: 'mcq', q: "5. Remote-access VPNs allow:", options: ["Only local users", "Mobile users to connect securely", "Server replication", "DNS tunneling"], correct: 1 },
            { type: 'mcq', q: "6. SSL VPNs typically require:", options: ["Dedicated VPN appliance", "Only a web browser", "Special routing hardware", "Fiber connections"], correct: 1 },
            { type: 'mcq', q: "7. IPsec provides:", options: ["Compression", "Confidentiality and integrity", "Network switching", "NAT management"], correct: 1 },
            { type: 'mcq', q: "8. Which IPsec protocol provides encryption?", options: ["AH", "ESP", "RIP", "OSPF"], correct: 1 },
            { type: 'mcq', q: "9. The key exchange protocol used by IPsec is:", options: ["DHCP", "BGP", "IKE", "ARP"], correct: 2 },
            { type: 'mcq', q: "10. Which type of VPN is managed by service providers?", options: ["SSL VPN", "MPLS VPN", "GRE VPN", "DMVPN"], correct: 1 },
            { type: 'mcq', q: "11. GRE tunnels support:", options: ["Only unicast", "Multicast and broadcast", "Encrypted only", "Layer 7 traffic"], correct: 1 },
            { type: 'mcq', q: "12. A disadvantage of GRE is:", options: ["No IPv6 support", "No built in encryption", "No routing support", "Low throughput"], correct: 1 },
            { type: 'mcq', q: "13. DMVPN uses which topology?", options: ["Bus", "Hub-and-spoke", "Ring", "Mesh only"], correct: 1 },
            { type: 'mcq', q: "14. In GRE over IPsec, the 'carrier protocol' is:", options: ["IP", "GRE", "ESP", "AH"], correct: 1 },
            { type: 'mcq', q: "15. AES supports key lengths up to:", options: ["64 bits", "128 bits", "256 bits", "512 bits"], correct: 2 },
            { type: 'mcq', q: "16. MD5 uses what key length?", options: ["64-bit", "128-bit", "160-bit", "256-bit"], correct: 1 },
            { type: 'mcq', q: "17. SHA uses what key length?", options: ["56-bit", "128-bit", "160-bit", "512-bit"], correct: 2 },
            { type: 'mcq', q: "18. Which authentication method scales poorly?", options: ["RSA certificates", "Pre shared keys", "Kerberos", "TACACS+"], correct: 1 },
            { type: 'mcq', q: "19. DH group 14 uses what key size?", options: ["1024 bits", "2048 bits", "4096 bits", "512 bits"], correct: 1 },
            { type: 'mcq', q: "20. IPsec VTI simplifies configuration by:", options: ["Eliminating routing", "Using virtual interfaces", "Replacing encryption", "Removing tunnels"], correct: 1 },
            { type: 'mcq', q: "21. Which VPN supports clientless access?", options: ["IPsec only", "SSL", "GRE", "MPLS"], correct: 1 },
            { type: 'mcq', q: "22. MPLS VPNs secure customer traffic by:", options: ["Encrypting every packet", "Logical separation using labels", "DNS filtering", "NAT translation"], correct: 1 },
            { type: 'mcq', q: "23. Encryption in site to site IPsec occurs:", options: ["End to end on each host", "Only between VPN gateways", "Only on routers", "Nowhere"], correct: 1 },
            { type: 'mcq', q: "24. Which needs a VPN client installed?", options: ["Clientless SSL", "Client based VPN", "MPLS", "GRE"], correct: 1 },
            { type: 'mcq', q: "25. ESP provides:", options: ["Authentication only", "Encryption only", "Both encryption and authentication", "Routing"], correct: 2 },
            { type: 'mcq', q: "26. AH provides:", options: ["Encryption only", "Authentication only", "Compression", "NAT traversal"], correct: 1 },
            { type: 'mcq', q: "27. Passenger protocol in GRE over IPsec:", options: ["GRE header", "Original packet", "ESP wrapper", "MPLS label"], correct: 1 },
            { type: 'mcq', q: "28. DMVPN allows:", options: ["No communication", "Only multicast", "Dynamic spoke to spoke tunnels", "DHCP"], correct: 2 },
            { type: 'mcq', q: "29. IPsec is defined by:", options: ["IEEE", "IETF", "ISO", "NIST"], correct: 1 },
            { type: 'mcq', q: "30. SEAL uses what key size?", options: ["40 bits", "160 bits", "256 bits", "512 bits"], correct: 1 },
            { type: 'mcq', q: "31. NOT a benefit of VPNs:", options: ["Cost savings", "Scalability", "Compatibility", "Increased physical infrastructure"], correct: 3 },
            { type: 'mcq', q: "32. SSL VPN authentication uses:", options: ["Tunneling only", "Digital certificates", "ARP tables", "OSPF"], correct: 1 },
            { type: 'mcq', q: "33. Which supports all IP based apps?", options: ["SSL", "IPsec", "GRE", "MPLS"], correct: 1 },
            { type: 'mcq', q: "34. IPsec operates at:", options: ["Layer 2", "Layer 3", "Layer 5", "Layer 7"], correct: 1 },
            { type: 'mcq', q: "35. DH groups supporting ECC:", options: ["1–5", "14–16", "19–21, 24", "All groups"], correct: 2 },
            { type: 'mcq', q: "36. Best for remote workers with full access:", options: ["Site to site", "SSL clientless", "Client based IPsec", "MPLS"], correct: 2 },
            { type: 'mcq', q: "37. MPLS forwards traffic using:", options: ["IP addresses", "Frames only", "Labels", "Hostnames"], correct: 2 },
            { type: 'mcq', q: "38. Purpose of IKE:", options: ["Encrypt data", "Exchange keys", "Route packets", "Add headers"], correct: 1 },
            { type: 'mcq', q: "39. VPN supporting broadcast:", options: ["GRE", "IPsec only", "MPLS L3", "None"], correct: 0 },
            { type: 'mcq', q: "40. Oldest algorithm:", options: ["AES", "SEAL", "DES", "3DES"], correct: 2 },
            { type: 'mcq', q: "41. Site to site IPsec requires:", options: ["VPN gateway", "Browser", "Fiber switch", "Load balancer"], correct: 0 },
            { type: 'mcq', q: "42. Integrity ensures:", options: ["No delay", "Data unmodified", "Always encrypted", "NAT bypass"], correct: 1 },
            { type: 'mcq', q: "43. Symmetric algorithm:", options: ["RSA", "AES", "DH", "IKE"], correct: 1 },
            { type: 'mcq', q: "44. VPN enables:", options: ["Public access", "Private communication over public networks", "Replacing routers", "Wireless only"], correct: 1 },
            { type: 'mcq', q: "45. Remote-access VPNs are:", options: ["Always on", "User initiated", "Hardware only", "Wireless only"], correct: 1 },
            { type: 'mcq', q: "46. IPsec framework components:", options: ["Fixed only", "Mix and match", "Vendor locked", "Hardware only"], correct: 1 },
            { type: 'mcq', q: "47. Confidentiality provided by:", options: ["SHA", "HMAC", "DES", "RSA"], correct: 2 },
            { type: 'mcq', q: "48. Transport protocol in GRE over IPsec:", options: ["GRE", "Passenger protocol", "IP", "OSPF"], correct: 2 },
            { type: 'mcq', q: "49. MPLS L2 VPNs emulate:", options: ["WAN links", "Ethernet LAN segments", "IPsec tunnels", "SSL"], correct: 1 },
            { type: 'mcq', q: "50. Smaller key sizes mean:", options: ["Stronger security", "Weaker security", "No effect", "Random"], correct: 1 }
        ]
    }
};
