const quizData = {
    courseTitle: "IoT",
    'tutorial-1': {
        title: "Tutorial 1",
        data: [
            { type: 'fill', q: "33. MQTT operates on a _________ / _________ communication model, where devices publish data to a broker and other devices subscribe to receive it.", answer: "Publish / Subscribe" },
            { type: 'fill', q: "34. Compared to HTTP, MQTT consumes _________ bandwidth and is more suitable for _________ devices.", answer: "Less; low-power or constrained" },
            { type: 'fill', q: "35. Edge computing processes data _________ the device to reduce latency and increase _________.", answer: "Near; privacy" },
            { type: 'fill', q: "36. In a hybrid IoT system, the edge handles _________ processing, while the cloud performs _________ analytics and storage.", answer: "Real-time; long-term" },
            { type: 'fill', q: "37. The communication layer in an IoT architecture is responsible for connecting devices through protocols such as _________, _________, or _________.", answer: "Wi-Fi, Zigbee, LTE" },
            { type: 'fill', q: "38. FreeRTOS manages _________ tasks on IoT devices, while Node-RED provides a _________ interface for flow-based programming.", answer: "Real-time; visual" },
            { type: 'fill', q: "39. In the smart agriculture case study, soil moisture and temperature sensors send data to an Arduino, which activates actuators like _________ and _________ to control irrigation.", answer: "Relays; solenoid valves" },
            { type: 'fill', q: "40. To ensure system robustness, IoT devices must include _________ calibration, redundancy, and _________ protection.", answer: "Sensor; environmental" }
        ]
    },

    'tutorial-2': {
        title: "Tutorial 2",
        data: [
            { type: 'fill', q: "1. HTTP uses the __________ communication model, where a client sends a request and the server responds.", answer: "Request–Response" },
            { type: 'fill', q: "2. In MQTT, the component that manages message routing between publishers and subscribers is called the __________.", answer: "Broker" },
            { type: 'fill', q: "3. CoAP is designed to work over the __________ transport protocol for lightweight communication.", answer: "UDP" },
            { type: 'fill', q: "4. The protocol best suited for constrained, battery-powered IoT devices is __________.", answer: "CoAP" },
            { type: 'fill', q: "5. MQTT typically runs over the __________ transport protocol to ensure reliable message delivery.", answer: "TCP" },
            { type: 'fill', q: "6. In MQTT, “QoS” stands for __________, which defines reliability levels for message delivery.", answer: "Quality of Service" },
            { type: 'fill', q: "7. 6LoWPAN is used for __________ over low-power wireless networks.", answer: "IPv6 compression" },
            { type: 'fill', q: "8. The protocol that provides message queuing and routing for enterprise IoT systems is __________.", answer: "AMQP" },
            { type: 'fill', q: "9. The __________ layer of the OSI model handles reliable data transfer in IoT networks.", answer: "Transport" },
            { type: 'fill', q: "10. The perception layer of IoT architecture mainly deals with __________ and __________.", answer: "Sensing and Actuating" },
            { type: 'fill', q: "11. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "12. The main drawback of HTTP for IoT applications is its __________ and __________ use.", answer: "High overhead and energy use" },
            { type: 'fill', q: "13. The __________ layer defines the physical transmission medium, such as wires or radio waves.", answer: "Physical" },
            { type: 'fill', q: "14. MQTT messages are organized by __________, which act as logical channels for communication.", answer: "Topics" },
            { type: 'fill', q: "15. CoAP ensures security using __________, which protects messages sent over UDP.", answer: "DTLS (Datagram Transport Layer Security)" }
        ]
    },

    'tutorial-3': {
        title: "Tutorial 3",
        data: [
            { type: 'fill', q: "1. An edge device in an IoT system is used to sense, process, and send __________.", answer: "Data locally" },
            { type: 'fill', q: "2. The main microcontroller used in the Arduino Uno board is __________.", answer: "ATmega328P" },
            { type: 'fill', q: "3. Every Arduino program (sketch) includes two main functions: __________ and __________.", answer: "setup(), loop()" },
            { type: 'fill', q: "4. The function used to read analog input from a sensor is __________.", answer: "analogRead()" },
            { type: 'fill', q: "5. The command Serial.begin(9600); is used to start __________ communication at a baud rate of 9600.", answer: "Serial" },
            { type: 'fill', q: "6. The abbreviation PWM stands for __________.", answer: "Pulse Width Modulation" },
            { type: 'fill', q: "7. The DHT11 sensor provides data as a __________ signal.", answer: "Digital" },
            { type: 'fill', q: "8. The main role of the ADC (Analog-to-Digital Converter) in Arduino is to convert analog signals into __________ data.", answer: "Digital" },
            { type: 'fill', q: "9. An actuator is a device that performs a physical __________ based on signal input.", answer: "Action" },
            { type: 'fill', q: "10. The command digitalWrite(13, HIGH); turns __________ the output at pin 13.", answer: "On" },
            { type: 'fill', q: "11. The command used to set a pin as input or output in Arduino is __________.", answer: "pinMode()" },
            { type: 'fill', q: "12. The Serial Monitor in Arduino is mainly used to visualize or __________ data output for debugging.", answer: "Debug" },
            { type: 'fill', q: "13. The analogRead() function in Arduino Uno returns values in the range of __________ to __________.", answer: "0 to 1023" },
            { type: 'fill', q: "14. The sensor used to measure light intensity is called a(n) __________.", answer: "LDR (Light Dependent Resistor)" },
            { type: 'fill', q: "15. The loop() function in Arduino runs __________ after setup() as long as the board is powered.", answer: "Repeatedly" }
        ]
    },

    'tutorial-4': {
        title: "Tutorial 4",
        data: [
            { type: 'fill', q: "1. A Raspberry Pi is best described as a __________ that can run an operating system.", answer: "A single-board computer that can run an operating system" },
            { type: 'fill', q: "2. The abbreviation GPIO stands for __________.", answer: "General Purpose Input/Output" },
            { type: 'fill', q: "3. On a Raspberry Pi, a digital HIGH signal corresponds to a voltage level of __________ volts.", answer: "3.3 volts." },
            { type: 'fill', q: "4. The most commonly used programming language for Raspberry Pi IoT projects is __________.", answer: "Python" },
            { type: 'fill', q: "5. The Python library used to easily control GPIO pins is called __________.", answer: "gpiozero" },
            { type: 'fill', q: "6. The default username on Raspberry Pi OS is __________.", answer: "pi" },
            { type: 'fill', q: "7. The command used to connect remotely to a Raspberry Pi via SSH is __________.", answer: "ssh pi@<IP address>" },
            { type: 'fill', q: "8. The gpiozero library in Python uses the __________ numbering system by default.", answer: "BCM numbering (GPIO numbers)" },
            { type: 'fill', q: "9. The command that turns on an LED connected to GPIO17 using gpiozero is __________.", answer: "led.on()" },
            { type: 'fill', q: "10. The command used to install a Python library such as paho-mqtt is __________.", answer: "pip install paho-mqtt" },
            { type: 'fill', q: "11. The communication protocol used by Raspberry Pi to interact with MQTT brokers is __________.", answer: "MQTT" },
            { type: 'fill', q: "12. The default baud rate for serial communication with Arduino is __________.", answer: "9600" },
            { type: 'fill', q: "13. The Python library used for handling serial communication is __________.", answer: "pyserial" },
            { type: 'fill', q: "14. In MQTT, the function client.publish() is used to __________.", answer: "Send (publish) messages to a topic" },
            { type: 'fill', q: "15. Raspberry Pi cannot directly perform low-level analog-to-digital conversion because it lacks a built-in __________.", answer: "ADC (Analog-to-Digital Converter)" }
        ]
    },

    'tutorial-5': {
        title: "Tutorial 5",
        data: [
            { type: 'fill', q: "1. The primary role of the edge layer in IoT is __________.", answer: "Sensor data collection and initial processing" },
            { type: 'fill', q: "2. The fog layer in IoT architecture acts as a __________.", answer: "Local gateway or intermediate processing node" },
            { type: 'fill', q: "3. The cloud layer is mainly responsible for __________.", answer: "Data aggregation, analytics, and dashboards" },
            { type: 'fill', q: "4. An example of fog hardware is __________.", answer: "Raspberry Pi" },
            { type: 'fill', q: "5. The main function of the fog layer is to __________.", answer: "Reduce bandwidth use and processing load on the cloud" },
            { type: 'fill', q: "6. The protocol that best suits communication between edge and cloud is __________.", answer: "MQTT" },
            { type: 'fill', q: "7. In IoT systems, HTTP is described as a __________ model with higher overhead.", answer: "Request/Response" },
            { type: 'fill', q: "8. In MQTT, the device that manages message routing is called a __________.", answer: "Broker" },
            { type: 'fill', q: "9. A cloud IoT platform example is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "10. The connectivity technology that offers the longest range but lowest data rate is __________.", answer: "LoRaWAN" },
            { type: 'fill', q: "11. One advantage of fog computing is that it __________.", answer: "Reduces latency by local processing" },
            { type: 'fill', q: "12. The component that is NOT part of IoT connectivity layers is __________.", answer: "BIOS Layer" },
            { type: 'fill', q: "13. Data is transmitted between devices using MQTT over the transport layer protocol __________.", answer: "TCP" },
            { type: 'fill', q: "14. The IoT communication model that allows many devices to share one central broker is __________.", answer: "Publish–Subscribe" },
            { type: 'fill', q: "15. One major advantage of cloud computing in IoT is __________.", answer: "Infinite storage and global data access" }
        ]
    },

    'tutorial-REV': {
        title: "Review (مراجعة شاملة وعشوائية)",
        data: [
            // 68 سؤالاً بترتيب عشوائي وترقيم متسلسل من 1 إلى 68
            { type: 'fill', q: "1. Every Arduino program (sketch) includes two main functions: __________ and __________.", answer: "setup(), loop()" },
            { type: 'fill', q: "2. The main role of the ADC (Analog-to-Digital Converter) in Arduino is to convert analog signals into __________ data.", answer: "Digital" },
            { type: 'fill', q: "3. The primary role of the edge layer in IoT is __________.", answer: "Sensor data collection and initial processing" },
            { type: 'fill', q: "4. The communication layer in an IoT architecture is responsible for connecting devices through protocols such as _________, _________, or _________.", answer: "Wi-Fi, Zigbee, LTE" },
            { type: 'fill', q: "5. The default baud rate for serial communication with Arduino is __________.", answer: "9600" },
            { type: 'fill', q: "6. The command used to install a Python library such as paho-mqtt is __________.", answer: "pip install paho-mqtt" },
            { type: 'fill', q: "7. The fog layer in IoT architecture acts as a __________.", answer: "Local gateway or intermediate processing node" },
            { type: 'fill', q: "8. The protocol best suited for constrained, battery-powered IoT devices is __________.", answer: "CoAP" },
            { type: 'fill', q: "9. Raspberry Pi cannot directly perform low-level analog-to-digital conversion because it lacks a built-in __________.", answer: "ADC (Analog-to-Digital Converter)" },
            { type: 'fill', q: "10. In a hybrid IoT system, the edge handles _________ processing, while the cloud performs _________ analytics and storage.", answer: "Real-time; long-term" },
            { type: 'fill', q: "11. The main drawback of HTTP for IoT applications is its __________ and __________ use.", answer: "High overhead and energy use" },
            { type: 'fill', q: "12. The sensor used to measure light intensity is called a(n) __________.", answer: "LDR (Light Dependent Resistor)" },
            { type: 'fill', q: "13. In MQTT, the component that manages message routing between publishers and subscribers is called the __________.", answer: "Broker" },
            { type: 'fill', q: "14. A Raspberry Pi is best described as a __________ that can run an operating system.", answer: "A single-board computer that can run an operating system" },
            { type: 'fill', q: "15. The command that turns on an LED connected to GPIO17 using gpiozero is __________.", answer: "led.on()" },
            { type: 'fill', q: "16. An actuator is a device that performs a physical __________ based on signal input.", answer: "Action" },
            { type: 'fill', q: "17. The command used to connect remotely to a Raspberry Pi via SSH is __________.", answer: "ssh pi@<IP address>" },
            { type: 'fill', q: "18. The protocol that provides message queuing and routing for enterprise IoT systems is __________.", answer: "AMQP" },
            { type: 'fill', q: "19. The Python library used for handling serial communication is __________.", answer: "pyserial" },
            { type: 'fill', q: "20. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "21. The loop() function in Arduino runs __________ after setup() as long as the board is powered.", answer: "Repeatedly" },
            { type: 'fill', q: "22. The cloud layer is mainly responsible for __________.", answer: "Data aggregation, analytics, and dashboards" },
            { type: 'fill', q: "23. In MQTT, “QoS” stands for __________, which defines reliability levels for message delivery.", answer: "Quality of Service" },
            { type: 'fill', q: "24. The function used to read analog input from a sensor is __________.", answer: "analogRead()" },
            { type: 'fill', q: "25. Edge computing processes data _________ the device to reduce latency and increase _________.", answer: "Near; privacy" },
            { type: 'fill', q: "26. The abbreviation GPIO stands for __________.", answer: "General Purpose Input/Output" },
            { type: 'fill', q: "27. The communication protocol used by Raspberry Pi to interact with MQTT brokers is __________.", answer: "MQTT" },
            { type: 'fill', q: "28. The protocol that best suits communication between edge and cloud is __________.", answer: "MQTT" },
            { type: 'fill', q: "29. The connectivity technology that offers the longest range but lowest data rate is __________.", answer: "LoRaWAN" },
            { type: 'fill', q: "30. The command used to set a pin as input or output in Arduino is __________.", answer: "pinMode()" },
            { type: 'fill', q: "31. MQTT typically runs over the __________ transport protocol to ensure reliable message delivery.", answer: "TCP" },
            { type: 'fill', q: "32. The main microcontroller used in the Arduino Uno board is __________.", answer: "ATmega328P" },
            { type: 'fill', q: "33. In IoT systems, HTTP is described as a __________ model with higher overhead.", answer: "Request/Response" },
            { type: 'fill', q: "34. MQTT operates on a _________ / _________ communication model, where devices publish data to a broker and other devices subscribe to receive it.", answer: "Publish / Subscribe" },
            { type: 'fill', q: "35. In the smart agriculture case study, soil moisture and temperature sensors send data to an Arduino, which activates actuators like _________ and _________ to control irrigation.", answer: "Relays; solenoid valves" },
            { type: 'fill', q: "36. The default username on Raspberry Pi OS is __________.", answer: "pi" },
            { type: 'fill', q: "37. The component that is NOT part of IoT connectivity layers is __________.", answer: "BIOS Layer" },
            { type: 'fill', q: "38. The command Serial.begin(9600); is used to start __________ communication at a baud rate of 9600.", answer: "Serial" },
            { type: 'fill', q: "39. The main function of the fog layer is to __________.", answer: "Reduce bandwidth use and processing load on the cloud" },
            { type: 'fill', q: "40. In MQTT, the device that manages message routing is called a __________.", answer: "Broker" },
            { type: 'fill', q: "41. The Serial Monitor in Arduino is mainly used to visualize or __________ data output for debugging.", answer: "Debug" },
            { type: 'fill', q: "42. The __________ layer of the OSI model handles reliable data transfer in IoT networks.", answer: "Transport" },
            { type: 'fill', q: "43. The DHT11 sensor provides data as a __________ signal.", answer: "Digital" },
            { type: 'fill', q: "44. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "45. The most commonly used programming language for Raspberry Pi IoT projects is __________.", answer: "Python" },
            { type: 'fill', q: "46. CoAP is designed to work over the __________ transport protocol for lightweight communication.", answer: "UDP" },
            { type: 'fill', q: "47. The analogRead() function in Arduino Uno returns values in the range of __________ to __________.", answer: "0 to 1023" },
            { type: 'fill', q: "48. One major advantage of cloud computing in IoT is __________.", answer: "Infinite storage and global data access" },
            { type: 'fill', q: "49. The IoT communication model that allows many devices to share one central broker is __________.", answer: "Publish–Subscribe" },
            { type: 'fill', q: "50. In MQTT, the function client.publish() is used to __________.", answer: "Send (publish) messages to a topic" },
            { type: 'fill', q: "51. On a Raspberry Pi, a digital HIGH signal corresponds to a voltage level of __________ volts.", answer: "3.3 volts." },
            { type: 'fill', q: "52. The perception layer of IoT architecture mainly deals with __________ and __________.", answer: "Sensing and Actuating" },
            { type: 'fill', q: "53. FreeRTOS manages _________ tasks on IoT devices, while Node-RED provides a _________ interface for flow-based programming.", answer: "Real-time; visual" },
            { type: 'fill', q: "54. An edge device in an IoT system is used to sense, process, and send __________.", answer: "Data locally" },
            { type: 'fill', q: "55. The abbreviation PWM stands for __________.", answer: "Pulse Width Modulation" },
            { type: 'fill', q: "56. Compared to HTTP, MQTT consumes _________ bandwidth and is more suitable for _________ devices.", answer: "Less; low-power or constrained" },
            { type: 'fill', q: "57. The __________ layer defines the physical transmission medium, such as wires or radio waves.", answer: "Physical" },
            { type: 'fill', q: "58. CoAP ensures security using __________, which protects messages sent over UDP.", answer: "DTLS (Datagram Transport Layer Security)" },
            { type: 'fill', q: "59. HTTP uses the __________ communication model, where a client sends a request and the server responds.", answer: "Request–Response" },
            { type: 'fill', q: "60. The Python library used to easily control GPIO pins is called __________.", answer: "gpiozero" },
            { type: 'fill', q: "61. An example of fog hardware is __________.", answer: "Raspberry Pi" },
            { type: 'fill', q: "62. 6LoWPAN is used for __________ over low-power wireless networks.", answer: "IPv6 compression" },
            { type: 'fill', q: "63. A cloud IoT platform example is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "64. Data is transmitted between devices using MQTT over the transport layer protocol __________.", answer: "TCP" },
            { type: 'fill', q: "65. To ensure system robustness, IoT devices must include _________ calibration, redundancy, and _________ protection.", answer: "Sensor; environmental" },
            { type: 'fill', q: "66. MQTT messages are organized by __________, which act as logical channels for communication.", answer: "Topics" },
            { type: 'fill', q: "67. The gpiozero library in Python uses the __________ numbering system by default.", answer: "BCM numbering (GPIO numbers)" },
            { type: 'fill', q: "68. One advantage of fog computing is that it __________.", answer: "Reduces latency by local processing" }
        ]
    }
};
