const quizData = {
    courseTitle: "IoT",
    'tutorial-1': {
        title: "Tutorial 2",
        data: [
            { type: 'fill', q: "1. HTTP uses the __________ communication model, where a client sends a request and the server responds.", answer: "Request–Response" },
            { type: 'fill', q: "2. In MQTT, the component that manages message routing between publishers and subscribers is called the __________.", answer: "Broker" },
            { type: 'fill', q: "3. CoAP is designed to work over the __________ transport protocol for lightweight communication.", answer: "UDP" },
            { type: 'fill', q: "4. The protocol best suited for constrained, battery-powered IoT devices is __________.", answer: "CoAP" },
            { type: 'fill', q: "5. MQTT typically runs over the __________ transport protocol to ensure reliable message delivery.", answer: "TCP" },
            { type: 'fill', q: "6. In MQTT, “QoS” stands for __________, which defines reliability levels for message delivery.", answer: "Quality of Service" },
            { type: 'fill', q: "7. 6LoWPAN is used for __________ over low-power wireless networks.", answer: "IPv6 compression" },
            { type: 'fill', q: "8. The protocol that provides message queuing and routing for enterprise IoT systems is __________.", answer: "AMQP" },
            { type: 'fill', q: "9. The __________ layer of the OSI model handles reliable data transfer in IoT networks.", answer: "Transport" },
            { type: 'fill', q: "10. The perception layer of IoT architecture mainly deals with __________ and __________.", answer: "Sensing and Actuating" },
            { type: 'fill', q: "11. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "12. The main drawback of HTTP for IoT applications is its __________ and __________ use.", answer: "High overhead and energy use" },
            { type: 'fill', q: "13. The __________ layer defines the physical transmission medium, such as wires or radio waves.", answer: "Physical" },
            { type: 'fill', q: "14. MQTT messages are organized by __________, which act as logical channels for communication.", answer: "Topics" },
            { type: 'fill', q: "15. CoAP ensures security using __________, which protects messages sent over UDP.", answer: "DTLS (Datagram Transport Layer Security)" }
        ]
    },
    'tutorial-2': {
        title: "Tutorial 3",
        data: [
            { type: 'fill', q: "1. An edge device in an IoT system is used to sense, process, and send __________.", answer: "Data locally" },
            { type: 'fill', q: "2. The main microcontroller used in the Arduino Uno board is __________.", answer: "ATmega328P" },
            { type: 'fill', q: "3. Every Arduino program (sketch) includes two main functions: __________ and __________.", answer: "setup(), loop()" },
            { type: 'fill', q: "4. The function used to read analog input from a sensor is __________.", answer: "analogRead()" },
            { type: 'fill', q: "5. The command Serial.begin(9600); is used to start __________ communication at a baud rate of 9600.", answer: "Serial" },
            { type: 'fill', q: "6. The abbreviation PWM stands for __________.", answer: "Pulse Width Modulation" },
            { type: 'fill', q: "7. The DHT11 sensor provides data as a __________ signal.", answer: "Digital" },
            { type: 'fill', q: "8. The main role of the ADC (Analog-to-Digital Converter) in Arduino is to convert analog signals into __________ data.", answer: "Digital" },
            { type: 'fill', q: "9. An actuator is a device that performs a physical __________ based on signal input.", answer: "Action" },
            { type: 'fill', q: "10. The command digitalWrite(13, HIGH); turns __________ the output at pin 13.", answer: "On" },
            { type: 'fill', q: "11. The command used to set a pin as input or output in Arduino is __________.", answer: "pinMode()" },
            { type: 'fill', q: "12. The Serial Monitor in Arduino is mainly used to visualize or __________ data output for debugging.", answer: "Debug" },
            { type: 'fill', q: "13. The analogRead() function in Arduino Uno returns values in the range of __________ to __________.", answer: "0 to 1023" },
            { type: 'fill', q: "14. The sensor used to measure light intensity is called a(n) __________.", answer: "LDR (Light Dependent Resistor)" },
            { type: 'fill', q: "15. The loop() function in Arduino runs __________ after setup() as long as the board is powered.", answer: "Repeatedly" }
        ]
    },
    'tutorial-3': {
        title: "Tutorial 4",
        data: [
            { type: 'fill', q: "1. A Raspberry Pi is best described as a __________ that can run an operating system.", answer: "A single-board computer that can run an operating system" },
            { type: 'fill', q: "2. The abbreviation GPIO stands for __________.", answer: "General Purpose Input/Output" },
            { type: 'fill', q: "3. On a Raspberry Pi, a digital HIGH signal corresponds to a voltage level of __________ volts.", answer: "3.3 volts" },
            { type: 'fill', q: "4. The most commonly used programming language for Raspberry Pi IoT projects is __________.", answer: "Python" },
            { type: 'fill', q: "5. The Python library used to easily control GPIO pins is called __________.", answer: "gpiozero" },
            { type: 'fill', q: "6. The default username on Raspberry Pi OS is __________.", answer: "pi" },
            { type: 'fill', q: "7. The command used to connect remotely to a Raspberry Pi via SSH is __________.", answer: "ssh pi@<IP address>" },
            { type: 'fill', q: "8. The gpiozero library in Python uses the __________ numbering system by default.", answer: "BCM numbering (GPIO numbers)" },
            { type: 'fill', q: "9. The command that turns on an LED connected to GPIO17 using gpiozero is __________.", answer: "led.on()" },
            { type: 'fill', q: "10. The command used to install a Python library such as paho-mqtt is __________.", answer: "pip install paho-mqtt" },
            { type: 'fill', q: "11. The communication protocol used by Raspberry Pi to interact with MQTT brokers is __________.", answer: "MQTT" },
            { type: 'fill', q: "12. The default baud rate for serial communication with Arduino is __________.", answer: "9600" },
            { type: 'fill', q: "13. The Python library used for handling serial communication is __________.", answer: "pyserial" },
            { type: 'fill', q: "14. In MQTT, the function client.publish() is used to __________.", answer: "Send (publish) messages to a topic" },
            { type: 'fill', q: "15. Raspberry Pi cannot directly perform low-level analog-to-digital conversion because it lacks a built-in __________.", answer: "ADC (Analog-to-Digital Converter)" }
        ]
    },
    'tutorial-4': {
        title: "Tutorial 5",
        data: [
            { type: 'fill', q: "1. The primary role of the edge layer in IoT is __________.", answer: "Sensor data collection and initial processing" },
            { type: 'fill', q: "2. The fog layer in IoT architecture acts as a __________.", answer: "Local gateway or intermediate processing node" },
            { type: 'fill', q: "3. The cloud layer is mainly responsible for __________.", answer: "Data aggregation, analytics, and dashboards" },
            { type: 'fill', q: "4. An example of fog hardware is __________.", answer: "Raspberry Pi" },
            { type: 'fill', q: "5. The main function of the fog layer is to __________.", answer: "Reduce bandwidth use and processing load on the cloud" },
            { type: 'fill', q: "6. The protocol that best suits communication between edge and cloud is __________.", answer: "MQTT" },
            { type: 'fill', q: "7. In IoT systems, HTTP is described as a __________ model with higher overhead.", answer: "Request/Response" },
            { type: 'fill', q: "8. In MQTT, the device that manages message routing is called a __________.", answer: "Broker" },
            { type: 'fill', q: "9. A cloud IoT platform example is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "10. The connectivity technology that offers the longest range but lowest data rate is __________.", answer: "LoRaWAN" },
            { type: 'fill', q: "11. One advantage of fog computing is that it __________.", answer: "Reduces latency by local processing" },
            { type: 'fill', q: "12. The component that is NOT part of IoT connectivity layers is __________.", answer: "BIOS Layer" },
            { type: 'fill', q: "13. Data is transmitted between devices using MQTT over the transport layer protocol __________.", answer: "TCP" },
            { type: 'fill', q: "14. The IoT communication model that allows many devices to share one central broker is __________.", answer: "Publish–Subscribe" },
            { type: 'fill', q: "15. One major advantage of cloud computing in IoT is __________.", answer: "Infinite storage and global data access" }
        ]
    },
    'tutorial-5': {
        title: "REV Sheet",
        data: [
            { type: 'fill', q: "1. IoT stands for __________.", answer: "Internet of Things" },
            { type: 'fill', q: "2. The three main layers of IoT architecture are __________, __________, and __________.", answer: "Perception, Network, Application" },
            { type: 'fill', q: "3. The main goal of IoT is to connect __________ to the Internet.", answer: "Physical devices" },
            { type: 'fill', q: "4. The transport protocol used by MQTT is __________.", answer: "TCP" },
            { type: 'fill', q: "5. CoAP is designed to work on __________.", answer: "UDP" },
            { type: 'fill', q: "6. The device that collects sensor data and performs initial processing is called an __________ device.", answer: "Edge" },
            { type: 'fill', q: "7. The programming language commonly used in IoT data analytics is __________.", answer: "Python" },
            { type: 'fill', q: "8. The acronym API stands for __________.", answer: "Application Programming Interface" },
            { type: 'fill', q: "9. MQTT uses the __________/__________ model.", answer: "Publish/Subscribe" },
            { type: 'fill', q: "10. The unique address assigned to a device in a network is called its __________.", answer: "IP address" },
            { type: 'fill', q: "11. The physical layer is responsible for __________.", answer: "Transmission of raw bits over a medium" },
            { type: 'fill', q: "12. The IoT device that converts a physical quantity into an electrical signal is a __________.", answer: "Sensor" },
            { type: 'fill', q: "13. The opposite of a sensor in IoT systems is an __________.", answer: "Actuator" },
            { type: 'fill', q: "14. In IoT security, data encryption ensures __________.", answer: "Confidentiality" },
            { type: 'fill', q: "15. The abbreviation Wi-Fi stands for __________.", answer: "Wireless Fidelity" },
            { type: 'fill', q: "16. A commonly used cloud platform for IoT projects is __________.", answer: "AWS IoT Core" },
            { type: 'fill', q: "17. The lightweight protocol ideal for sensor networks is __________.", answer: "CoAP" },
            { type: 'fill', q: "18. A MAC address uniquely identifies a device at the __________ layer.", answer: "Data Link" },
            { type: 'fill', q: "19. The protocol used to obtain an IP address automatically is __________.", answer: "DHCP" },
            { type: 'fill', q: "20. LoRaWAN operates in the __________ frequency band.", answer: "Sub-GHz (Low frequency)" },
            { type: 'fill', q: "21. The abbreviation JSON stands for __________.", answer: "JavaScript Object Notation" },
            { type: 'fill', q: "22. A microcontroller differs from a microprocessor by having built-in __________.", answer: "Memory and I/O interfaces" },
            { type: 'fill', q: "23. The most common microcontroller platform for IoT prototyping is __________.", answer: "Arduino" },
            { type: 'fill', q: "24. The layer responsible for routing packets is the __________ layer.", answer: "Network" },
            { type: 'fill', q: "25. The most common version of IP used in IoT today is __________.", answer: "IPv6" },
            { type: 'fill', q: "26. The IoT technology used for smart meters and city infrastructure is __________.", answer: "NB-IoT" },
            { type: 'fill', q: "27. BLE stands for __________.", answer: "Bluetooth Low Energy" },
            { type: 'fill', q: "28. A gateway connects local IoT devices to the __________.", answer: "Cloud or Internet" },
            { type: 'fill', q: "29. DTLS provides security for __________ based protocols.", answer: "UDP" },
            { type: 'fill', q: "30. The communication protocol used by most web browsers is __________.", answer: "HTTP" },
            { type: 'fill', q: "31. A sensor node typically consists of a sensor, processor, power unit, and __________.", answer: "Transceiver" },
            { type: 'fill', q: "32. The process of converting analog data into digital form is called __________.", answer: "Analog-to-Digital Conversion" },
            { type: 'fill', q: "33. A cloud dashboard is used to __________ collected IoT data.", answer: "Visualize or monitor" },
            { type: 'fill', q: "34. The MQTT client command to subscribe to a topic is __________.", answer: "client.subscribe()" },
            { type: 'fill', q: "35. The delay between data transmission and reception is called __________.", answer: "Latency" },
            { type: 'fill', q: "36. The primary IoT protocol for messaging reliability and small packet overhead is __________.", answer: "MQTT" },
            { type: 'fill', q: "37. IPv6 uses addresses that are __________ bits long.", answer: "128" },
            { type: 'fill', q: "38. The term interoperability in IoT refers to __________.", answer: "Different devices working together seamlessly" },
            { type: 'fill', q: "39. An IoT system’s scalability refers to its ability to __________.", answer: "Handle more devices and data efficiently" },
            { type: 'fill', q: "40. The fog layer helps reduce __________ and __________.", answer: "Latency and bandwidth usage" },
            { type: 'fill', q: "41. A security challenge in IoT is due to devices having __________ resources.", answer: "Limited" },
            { type: 'fill', q: "42. The encryption protocol used in secure web communication is __________.", answer: "TLS (Transport Layer Security)" },
            { type: 'fill', q: "43. IoT analytics focuses on turning __________ into insights.", answer: "Raw data" },
            { type: 'fill', q: "44. A common lightweight data format used in IoT APIs is __________.", answer: "JSON" },
            { type: 'fill', q: "45. The layer that defines communication protocols and routing is the __________ layer.", answer: "Network" },
            { type: 'fill', q: "46. Cloud computing provides IoT with __________ and __________.", answer: "Scalability and storage" },
            { type: 'fill', q: "47. The protocol that allows devices to discover each other automatically is __________.", answer: "mDNS" },
            { type: 'fill', q: "48. In an IoT ecosystem, data security includes encryption, authentication, and __________.", answer: "Integrity" },
            { type: 'fill', q: "49. The MQTT message types include CONNECT, PUBLISH, and __________.", answer: "SUBSCRIBE" },
            { type: 'fill', q: "50. The programming platform Node-RED is used for __________.", answer: "IoT flow-based development" },
            { type: 'fill', q: "51. The part of IoT that connects sensors to networks is called the __________ layer.", answer: "Perception" },
            { type: 'fill', q: "52. A smart thermostat is an example of an IoT __________ device.", answer: "Consumer" },
            { type: 'fill', q: "53. The delay-sensitive IoT applications include __________ systems.", answer: "Real-time control" },
            { type: 'fill', q: "54. The security model that ensures only authorized users can access devices is __________.", answer: "Authentication" },
            { type: 'fill', q: "55. The communication technology with the shortest range is __________.", answer: "Bluetooth" },
            { type: 'fill', q: "56. The IoT concept of connecting any device, anytime, anywhere is called __________.", answer: "Ubiquitous connectivity" },
            { type: 'fill', q: "57. The device used to convert digital data into physical movement is called an __________.", answer: "Actuator" },
            { type: 'fill', q: "58. The protocol that enables secure communication between web clients and servers is __________.", answer: "HTTPS" },
            { type: 'fill', q: "59. The IoT system that automatically controls lighting based on motion detection is an example of a __________ system.", answer: "Smart home automation" },
            { type: 'fill', q: "60. The main challenge of large-scale IoT deployment is ensuring data __________ and device __________.", answer: "Security and interoperability" }
        ]
    }
};

