const quizData = {
    courseTitle: "IoT",
    
    'tutorial-1': {
        title: "Tutorial 1",
        data: [
            { type: 'fill', q: "33. MQTT operates on a _________ / _________ communication model, where devices publish data to a broker and other devices subscribe to receive it.", answer: "Publish / Subscribe" },
            { type: 'fill', q: "34. Compared to HTTP, MQTT consumes _________ bandwidth and is more suitable for _________ devices.", answer: "Less; low-power or constrained" },
            { type: 'fill', q: "35. Edge computing processes data _________ the device to reduce latency and increase _________.", answer: "Near; privacy" },
            { type: 'fill', q: "36. In a hybrid IoT system, the edge handles _________ processing, while the cloud performs _________ analytics and storage.", answer: "Real-time; long-term" },
            { type: 'fill', q: "37. The communication layer in an IoT architecture is responsible for connecting devices through protocols such as _________, _________, or _________.", answer: "Wi-Fi, Zigbee, LTE" },
            { type: 'fill', q: "38. FreeRTOS manages _________ tasks on IoT devices, while Node-RED provides a _________ interface for flow-based programming.", answer: "Real-time; visual" },
            { type: 'fill', q: "39. In the smart agriculture case study, soil moisture and temperature sensors send data to an Arduino, which activates actuators like _________ and _________ to control irrigation.", answer: "Relays; solenoid valves" },
            { type: 'fill', q: "40. To ensure system robustness, IoT devices must include _________ calibration, redundancy, and _________ protection.", answer: "Sensor; environmental" }
        ]
    },

    'tutorial-2': {
        title: "Tutorial 2",
        data: [
            { type: 'fill', q: "1. HTTP uses the __________ communication model, where a client sends a request and the server responds.", answer: "Request–Response" },
            { type: 'fill', q: "2. In MQTT, the component that manages message routing between publishers and subscribers is called the __________.", answer: "Broker" },
            { type: 'fill', q: "3. CoAP is designed to work over the __________ transport protocol for lightweight communication.", answer: "UDP" },
            { type: 'fill', q: "4. The protocol best suited for constrained, battery-powered IoT devices is __________.", answer: "CoAP" },
            { type: 'fill', q: "5. MQTT typically runs over the __________ transport protocol to ensure reliable message delivery.", answer: "TCP" },
            { type: 'fill', q: "6. In MQTT, “QoS” stands for __________, which defines reliability levels for message delivery.", answer: "Quality of Service" },
            { type: 'fill', q: "7. 6LoWPAN is used for __________ over low-power wireless networks.", answer: "IPv6 compression" },
            { type: 'fill', q: "8. The protocol that provides message queuing and routing for enterprise IoT systems is __________.", answer: "AMQP" },
            { type: 'fill', q: "9. The __________ layer of the OSI model handles reliable data transfer in IoT networks.", answer: "Transport" },
            { type: 'fill', q: "10. The perception layer of IoT architecture mainly deals with __________ and __________.", answer: "Sensing and Actuating" },
            { type: 'fill', q: "11. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "12. The main drawback of HTTP for IoT applications is its __________ and __________ use.", answer: "High overhead and energy use" },
            { type: 'fill', q: "13. The __________ layer defines the physical transmission medium, such as wires or radio waves.", answer: "Physical" },
            { type: 'fill', q: "14. MQTT messages are organized by __________, which act as logical channels for communication.", answer: "Topics" },
            { type: 'fill', q: "15. CoAP ensures security using __________, which protects messages sent over UDP.", answer: "DTLS (Datagram Transport Layer Security)" }
        ]
    },

    'tutorial-3': {
        title: "Tutorial 3",
        data: [
            { type: 'fill', q: "1. An edge device in an IoT system is used to sense, process, and send __________.", answer: "Data locally" },
            { type: 'fill', q: "2. The main microcontroller used in the Arduino Uno board is __________.", answer: "ATmega328P" },
            { type: 'fill', q: "3. Every Arduino program (sketch) includes two main functions: __________ and __________.", answer: "setup(), loop()" },
            { type: 'fill', q: "4. The function used to read analog input from a sensor is __________.", answer: "analogRead()" },
            { type: 'fill', q: "5. The command Serial.begin(9600); is used to start __________ communication at a baud rate of 9600.", answer: "Serial" },
            { type: 'fill', q: "6. The abbreviation PWM stands for __________.", answer: "Pulse Width Modulation" },
            { type: 'fill', q: "7. The DHT11 sensor provides data as a __________ signal.", answer: "Digital" },
            { type: 'fill', q: "8. The main role of the ADC (Analog-to-Digital Converter) in Arduino is to convert analog signals into __________ data.", answer: "Digital" },
            { type: 'fill', q: "9. An actuator is a device that performs a physical __________ based on signal input.", answer: "Action" },
            { type: 'fill', q: "10. The command digitalWrite(13, HIGH); turns __________ the output at pin 13.", answer: "On" },
            { type: 'fill', q: "11. The command used to set a pin as input or output in Arduino is __________.", answer: "pinMode()" },
            { type: 'fill', q: "12. The Serial Monitor in Arduino is mainly used to visualize or __________ data output for debugging.", answer: "Debug" },
            { type: 'fill', q: "13. The analogRead() function in Arduino Uno returns values in the range of __________ to __________.", answer: "0 to 1023" },
            { type: 'fill', q: "14. The sensor used to measure light intensity is called a(n) __________.", answer: "LDR (Light Dependent Resistor)" },
            { type: 'fill', q: "15. The loop() function in Arduino runs __________ after setup() as long as the board is powered.", answer: "Repeatedly" }
        ]
    },

    'tutorial-4': {
        title: "Tutorial 4",
        data: [
            { type: 'fill', q: "1. A Raspberry Pi is best described as a __________ that can run an operating system.", answer: "A single-board computer that can run an operating system" },
            { type: 'fill', q: "2. The abbreviation GPIO stands for __________.", answer: "General Purpose Input/Output" },
            { type: 'fill', q: "3. On a Raspberry Pi, a digital HIGH signal corresponds to a voltage level of __________ volts.", answer: "3.3 volts." },
            { type: 'fill', q: "4. The most commonly used programming language for Raspberry Pi IoT projects is __________.", answer: "Python" },
            { type: 'fill', q: "5. The Python library used to easily control GPIO pins is called __________.", answer: "gpiozero" },
            { type: 'fill', q: "6. The default username on Raspberry Pi OS is __________.", answer: "pi" },
            { type: 'fill', q: "7. The command used to connect remotely to a Raspberry Pi via SSH is __________.", answer: "ssh pi@<IP address>" },
            { type: 'fill', q: "8. The gpiozero library in Python uses the __________ numbering system by default.", answer: "BCM numbering (GPIO numbers)" },
            { type: 'fill', q: "9. The command that turns on an LED connected to GPIO17 using gpiozero is __________.", answer: "led.on()" },
            { type: 'fill', q: "10. The command used to install a Python library such as paho-mqtt is __________.", answer: "pip install paho-mqtt" },
            { type: 'fill', q: "11. The communication protocol used by Raspberry Pi to interact with MQTT brokers is __________.", answer: "MQTT" },
            { type: 'fill', q: "12. The default baud rate for serial communication with Arduino is __________.", answer: "9600" },
            { type: 'fill', q: "13. The Python library used for handling serial communication is __________.", answer: "pyserial" },
            { type: 'fill', q: "14. In MQTT, the function client.publish() is used to __________.", answer: "Send (publish) messages to a topic" },
            { type: 'fill', q: "15. Raspberry Pi cannot directly perform low-level analog-to-digital conversion because it lacks a built-in __________.", answer: "ADC (Analog-to-Digital Converter)" }
        ]
    },

    'tutorial-5': {
        title: "Tutorial 5",
        data: [
            { type: 'fill', q: "1. The primary role of the edge layer in IoT is __________.", answer: "Sensor data collection and initial processing" },
            { type: 'fill', q: "2. The fog layer in IoT architecture acts as a __________.", answer: "Local gateway or intermediate processing node" },
            { type: 'fill', q: "3. The cloud layer is mainly responsible for __________.", answer: "Data aggregation, analytics, and dashboards" },
            { type: 'fill', q: "4. An example of fog hardware is __________.", answer: "Raspberry Pi" },
            { type: 'fill', q: "5. The main function of the fog layer is to __________.", answer: "Reduce bandwidth use and processing load on the cloud" },
            { type: 'fill', q: "6. The protocol that best suits communication between edge and cloud is __________.", answer: "MQTT" },
            { type: 'fill', q: "7. In IoT systems, HTTP is described as a __________ model with higher overhead.", answer: "Request/Response" },
            { type: 'fill', q: "8. In MQTT, the device that manages message routing is called a __________.", answer: "Broker" },
            { type: 'fill', q: "9. A cloud IoT platform example is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "10. The connectivity technology that offers the longest range but lowest data rate is __________.", answer: "LoRaWAN" },
            { type: 'fill', q: "11. One advantage of fog computing is that it __________.", answer: "Reduces latency by local processing" },
            { type: 'fill', q: "12. The component that is NOT part of IoT connectivity layers is __________.", answer: "BIOS Layer" },
            { type: 'fill', q: "13. Data is transmitted between devices using MQTT over the transport layer protocol __________.", answer: "TCP" },
            { type: 'fill', q: "14. The IoT communication model that allows many devices to share one central broker is __________.", answer: "Publish–Subscribe" },
            { type: 'fill', q: "15. One major advantage of cloud computing in IoT is __________.", answer: "Infinite storage and global data access" }
        ]
    },

    'tutorial-6': {
        title: "Tutorial 6",
        data: [
            { type: 'fill', q: "1. IoT data is best described as __________.", answer: "Time-stamped, continuous, and machine-generated" },
            { type: 'fill', q: "2. The most common format used for transmitting IoT data is __________.", answer: "JSON" },
            { type: 'fill', q: "3. Time-series data represents __________.", answer: "Sensor data indexed by time" },
            { type: 'fill', q: "4. A cloud-based IoT data visualization platform is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "5. The Python library commonly used for data analysis is __________.", answer: "pandas" },
            { type: 'fill', q: "6. The type of database that InfluxDB represents is __________.", answer: "Time-Series" },
            { type: 'fill', q: "7. The data format that is human-readable and lightweight is __________.", answer: "JSON" },
            { type: 'fill', q: "8. A benefit of performing data analytics in the fog layer is __________.", answer: "Reduces latency and cloud costs" },
            { type: 'fill', q: "9. The tool that can generate interactive IoT dashboards is __________.", answer: "Grafana" },
            { type: 'fill', q: "10. The purpose of data cleaning in IoT analytics is __________.", answer: "To ensure data accuracy and reliability" },
            { type: 'fill', q: "11. The Python library used to visualize data through graphs is __________.", answer: "matplotlib" },
            { type: 'fill', q: "12. The database typically used for simple IoT storage on Raspberry Pi is __________.", answer: "SQLite" },
            { type: 'fill', q: "13. The acronym CSV stands for __________.", answer: "Comma Separated Values" },
            { type: 'fill', q: "14. The Python command that writes IoT data into a file is __________.", answer: "write()" },
            { type: 'fill', q: "15. The step that comes last in the IoT data lifecycle is __________.", answer: "Visualization and Action" }
        ]
    },

    'tutorial-7': {
        title: "Tutorial 7",
        data: [
            { type: 'fill', q: "1. The “C” in the CIA security triad stands for __________.", answer: "Confidentiality" },
            { type: 'fill', q: "2. The protocol that adds TLS encryption to MQTT communication is __________.", answer: "MQTTS" },
            { type: 'fill', q: "3. A symmetrical encryption algorithm used in IoT is __________.", answer: "AES" },
            { type: 'fill', q: "4. The main purpose of firmware signing is __________.", answer: "To authenticate software origin" },
            { type: 'fill', q: "5. The Mirai botnet attack exploited __________.", answer: "Weak default passwords on IoT devices" },
            { type: 'fill', q: "6. The IoT security measure that ensures data is not altered during transmission is __________.", answer: "Integrity" },
            { type: 'fill', q: "7. TLS operates at the __________ layer of the OSI model.", answer: "Transport" },
            { type: 'fill', q: "8. Multi-factor authentication (MFA) requires __________.", answer: "Two or more verification factors" },
            { type: 'fill', q: "9. The IoT security principle that ensures users have only the permissions they need is __________.", answer: "Role-based access control (RBAC)" },
            { type: 'fill', q: "10. CoAPS is the secured version of the __________ protocol.", answer: "CoAP" },
            { type: 'fill', q: "11. The following is NOT a recommended IoT security practice: __________.", answer: "Open APIs without authentication" },
            { type: 'fill', q: "12. The acronym OWASP stands for __________.", answer: "Open Web Application Security Project" },
            { type: 'fill', q: "13. The cryptographic method that uses public and private keys is __________.", answer: "Asymmetric encryption" },
            { type: 'fill', q: "14. GDPR primarily protects __________.", answer: "Personal data of EU citizens" },
            { type: 'fill', q: "15. Data availability in IoT systems is ensured by __________.", answer: "Redundant systems and fail-over mechanisms" }
        ]
    },

    'tutorial-8': {
        title: "Tutorial 8",
        data: [
            { type: 'fill', q: "1. An example of an IoT application in agriculture is __________.", answer: "Soil moisture monitoring and automated irrigation" },
            { type: 'fill', q: "2. The component that acts as the edge device in a smart greenhouse system is __________.", answer: "Arduino with sensors" },
            { type: 'fill', q: "3. In an IoT system, the fog layer is typically represented by __________.", answer: "Raspberry Pi or Gateway" },
            { type: 'fill', q: "4. The cloud layer in IoT plays the role of __________.", answer: "Long-term data storage and analytics" },
            { type: 'fill', q: "5. The protocol commonly used for IoT data upload to cloud dashboards is __________.", answer: "MQTT" },
            { type: 'fill', q: "6. The free platform most often used for cloud-based IoT visualization is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "7. In a smart home application, the device that usually controls lighting systems is __________.", answer: "Arduino microcontroller" },
            { type: 'fill', q: "8. The most important design step before starting an IoT project is __________.", answer: "Drawing the system architecture diagram" },
            { type: 'fill', q: "9. A key advantage of using fog computing in IoT is __________.", answer: "Reduced bandwidth and latency" },
            { type: 'fill', q: "10. A tool that can be used to visualize IoT data locally on Raspberry Pi is __________.", answer: "Matplotlib" },
            { type: 'fill', q: "11. In an IoT project, the component that handles decision logic or automation is __________.", answer: "Gateway/Fog node" },
            { type: 'fill', q: "12. The software design practice that improves IoT system scalability is __________.", answer: "Modular programming and reusable functions" },
            { type: 'fill', q: "13. The best way to protect IoT data during cloud upload is __________.", answer: "Use TLS encryption (HTTPS or MQTTS)" },
            { type: 'fill', q: "14. A key evaluation metric for IoT project performance is __________.", answer: "Response time and reliability" },
            { type: 'fill', q: "15. The document that summarizes an IoT project’s system design, data flow, and results is __________.", answer: "Project Report" }
        ]
    },

    'tutorial-FINAL': {
        title: "الشاملة (جميع أسئلة أكمل من 1 إلى 8)",
        data: [
            // Tutorial 1
            { type: 'fill', q: "1. MQTT operates on a _________ / _________ communication model, where devices publish data to a broker and other devices subscribe to receive it.", answer: "Publish / Subscribe" },
            { type: 'fill', q: "2. Compared to HTTP, MQTT consumes _________ bandwidth and is more suitable for _________ devices.", answer: "Less; low-power or constrained" },
            { type: 'fill', q: "3. Edge computing processes data _________ the device to reduce latency and increase _________.", answer: "Near; privacy" },
            { type: 'fill', q: "4. In a hybrid IoT system, the edge handles _________ processing, while the cloud performs _________ analytics and storage.", answer: "Real-time; long-term" },
            { type: 'fill', q: "5. The communication layer in an IoT architecture is responsible for connecting devices through protocols such as _________, _________, or _________.", answer: "Wi-Fi, Zigbee, LTE" },
            { type: 'fill', q: "6. FreeRTOS manages _________ tasks on IoT devices, while Node-RED provides a _________ interface for flow-based programming.", answer: "Real-time; visual" },
            { type: 'fill', q: "7. In the smart agriculture case study, soil moisture and temperature sensors send data to an Arduino, which activates actuators like _________ and _________ to control irrigation.", answer: "Relays; solenoid valves" },
            { type: 'fill', q: "8. To ensure system robustness, IoT devices must include _________ calibration, redundancy, and _________ protection.", answer: "Sensor; environmental" },
            // Tutorial 2
            { type: 'fill', q: "9. HTTP uses the __________ communication model, where a client sends a request and the server responds.", answer: "Request–Response" },
            { type: 'fill', q: "10. In MQTT, the component that manages message routing between publishers and subscribers is called the __________.", answer: "Broker" },
            { type: 'fill', q: "11. CoAP is designed to work over the __________ transport protocol for lightweight communication.", answer: "UDP" },
            { type: 'fill', q: "12. The protocol best suited for constrained, battery-powered IoT devices is __________.", answer: "CoAP" },
            { type: 'fill', q: "13. MQTT typically runs over the __________ transport protocol to ensure reliable message delivery.", answer: "TCP" },
            { type: 'fill', q: "14. In MQTT, “QoS” stands for __________, which defines reliability levels for message delivery.", answer: "Quality of Service" },
            { type: 'fill', q: "15. 6LoWPAN is used for __________ over low-power wireless networks.", answer: "IPv6 compression" },
            { type: 'fill', q: "16. The protocol that provides message queuing and routing for enterprise IoT systems is __________.", answer: "AMQP" },
            { type: 'fill', q: "17. The __________ layer of the OSI model handles reliable data transfer in IoT networks.", answer: "Transport" },
            { type: 'fill', q: "18. The perception layer of IoT architecture mainly deals with __________ and __________.", answer: "Sensing and Actuating" },
            { type: 'fill', q: "19. The protocol that uses REST-style methods (GET, POST, PUT, DELETE) is __________.", answer: "CoAP" },
            { type: 'fill', q: "20. The main drawback of HTTP for IoT applications is its __________ and __________ use.", answer: "High overhead and energy use" },
            { type: 'fill', q: "21. The __________ layer defines the physical transmission medium, such as wires or radio waves.", answer: "Physical" },
            { type: 'fill', q: "22. MQTT messages are organized by __________, which act as logical channels for communication.", answer: "Topics" },
            { type: 'fill', q: "23. CoAP ensures security using __________, which protects messages sent over UDP.", answer: "DTLS (Datagram Transport Layer Security)" },
            // Tutorial 3
            { type: 'fill', q: "24. An edge device in an IoT system is used to sense, process, and send __________.", answer: "Data locally" },
            { type: 'fill', q: "25. The main microcontroller used in the Arduino Uno board is __________.", answer: "ATmega328P" },
            { type: 'fill', q: "26. Every Arduino program (sketch) includes two main functions: __________ and __________.", answer: "setup(), loop()" },
            { type: 'fill', q: "27. The function used to read analog input from a sensor is __________.", answer: "analogRead()" },
            { type: 'fill', q: "28. The command Serial.begin(9600); is used to start __________ communication at a baud rate of 9600.", answer: "Serial" },
            { type: 'fill', q: "29. The abbreviation PWM stands for __________.", answer: "Pulse Width Modulation" },
            { type: 'fill', q: "30. The DHT11 sensor provides data as a __________ signal.", answer: "Digital" },
            { type: 'fill', q: "31. The main role of the ADC (Analog-to-Digital Converter) in Arduino is to convert analog signals into __________ data.", answer: "Digital" },
            { type: 'fill', q: "32. An actuator is a device that performs a physical __________ based on signal input.", answer: "Action" },
            { type: 'fill', q: "33. The command digitalWrite(13, HIGH); turns __________ the output at pin 13.", answer: "On" },
            { type: 'fill', q: "34. The command used to set a pin as input or output in Arduino is __________.", answer: "pinMode()" },
            { type: 'fill', q: "35. The Serial Monitor in Arduino is mainly used to visualize or __________ data output for debugging.", answer: "Debug" },
            { type: 'fill', q: "36. The analogRead() function in Arduino Uno returns values in the range of __________ to __________.", answer: "0 to 1023" },
            { type: 'fill', q: "37. The sensor used to measure light intensity is called a(n) __________.", answer: "LDR (Light Dependent Resistor)" },
            { type: 'fill', q: "38. The loop() function in Arduino runs __________ after setup() as long as the board is powered.", answer: "Repeatedly" },
            // Tutorial 4
            { type: 'fill', q: "39. A Raspberry Pi is best described as a __________ that can run an operating system.", answer: "A single-board computer that can run an operating system" },
            { type: 'fill', q: "40. The abbreviation GPIO stands for __________.", answer: "General Purpose Input/Output" },
            { type: 'fill', q: "41. On a Raspberry Pi, a digital HIGH signal corresponds to a voltage level of __________ volts.", answer: "3.3 volts." },
            { type: 'fill', q: "42. The most commonly used programming language for Raspberry Pi IoT projects is __________.", answer: "Python" },
            { type: 'fill', q: "43. The Python library used to easily control GPIO pins is called __________.", answer: "gpiozero" },
            { type: 'fill', q: "44. The default username on Raspberry Pi OS is __________.", answer: "pi" },
            { type: 'fill', q: "45. The command used to connect remotely to a Raspberry Pi via SSH is __________.", answer: "ssh pi@<IP address>" },
            { type: 'fill', q: "46. The gpiozero library in Python uses the __________ numbering system by default.", answer: "BCM numbering (GPIO numbers)" },
            { type: 'fill', q: "47. The command that turns on an LED connected to GPIO17 using gpiozero is __________.", answer: "led.on()" },
            { type: 'fill', q: "48. The command used to install a Python library such as paho-mqtt is __________.", answer: "pip install paho-mqtt" },
            { type: 'fill', q: "49. The communication protocol used by Raspberry Pi to interact with MQTT brokers is __________.", answer: "MQTT" },
            { type: 'fill', q: "50. The default baud rate for serial communication with Arduino is __________.", answer: "9600" },
            { type: 'fill', q: "51. The Python library used for handling serial communication is __________.", answer: "pyserial" },
            { type: 'fill', q: "52. In MQTT, the function client.publish() is used to __________.", answer: "Send (publish) messages to a topic" },
            { type: 'fill', q: "53. Raspberry Pi cannot directly perform low-level analog-to-digital conversion because it lacks a built-in __________.", answer: "ADC (Analog-to-Digital Converter)" },
            // Tutorial 5
            { type: 'fill', q: "54. The primary role of the edge layer in IoT is __________.", answer: "Sensor data collection and initial processing" },
            { type: 'fill', q: "55. The fog layer in IoT architecture acts as a __________.", answer: "Local gateway or intermediate processing node" },
            { type: 'fill', q: "56. The cloud layer is mainly responsible for __________.", answer: "Data aggregation, analytics, and dashboards" },
            { type: 'fill', q: "57. An example of fog hardware is __________.", answer: "Raspberry Pi" },
            { type: 'fill', q: "58. The main function of the fog layer is to __________.", answer: "Reduce bandwidth use and processing load on the cloud" },
            { type: 'fill', q: "59. The protocol that best suits communication between edge and cloud is __________.", answer: "MQTT" },
            { type: 'fill', q: "60. In IoT systems, HTTP is described as a __________ model with higher overhead.", answer: "Request/Response" },
            { type: 'fill', q: "61. In MQTT, the device that manages message routing is called a __________.", answer: "Broker" },
            { type: 'fill', q: "62. A cloud IoT platform example is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "63. The connectivity technology that offers the longest range but lowest data rate is __________.", answer: "LoRaWAN" },
            { type: 'fill', q: "64. One advantage of fog computing is that it __________.", answer: "Reduces latency by local processing" },
            { type: 'fill', q: "65. The component that is NOT part of IoT connectivity layers is __________.", answer: "BIOS Layer" },
            { type: 'fill', q: "66. Data is transmitted between devices using MQTT over the transport layer protocol __________.", answer: "TCP" },
            { type: 'fill', q: "67. The IoT communication model that allows many devices to share one central broker is __________.", answer: "Publish–Subscribe" },
            { type: 'fill', q: "68. One major advantage of cloud computing in IoT is __________.", answer: "Infinite storage and global data access" },
            // Tutorial 6
            { type: 'fill', q: "69. IoT data is best described as __________.", answer: "Time-stamped, continuous, and machine-generated" },
            { type: 'fill', q: "70. The most common format used for transmitting IoT data is __________.", answer: "JSON" },
            { type: 'fill', q: "71. Time-series data represents __________.", answer: "Sensor data indexed by time" },
            { type: 'fill', q: "72. A cloud-based IoT data visualization platform is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "73. The Python library commonly used for data analysis is __________.", answer: "pandas" },
            { type: 'fill', q: "74. The type of database that InfluxDB represents is __________.", answer: "Time-Series" },
            { type: 'fill', q: "75. The data format that is human-readable and lightweight is __________.", answer: "JSON" },
            { type: 'fill', q: "76. A benefit of performing data analytics in the fog layer is __________.", answer: "Reduces latency and cloud costs" },
            { type: 'fill', q: "77. The tool that can generate interactive IoT dashboards is __________.", answer: "Grafana" },
            { type: 'fill', q: "78. The purpose of data cleaning in IoT analytics is __________.", answer: "To ensure data accuracy and reliability" },
            { type: 'fill', q: "79. The Python library used to visualize data through graphs is __________.", answer: "matplotlib" },
            { type: 'fill', q: "80. The database typically used for simple IoT storage on Raspberry Pi is __________.", answer: "SQLite" },
            { type: 'fill', q: "81. The acronym CSV stands for __________.", answer: "Comma Separated Values" },
            { type: 'fill', q: "82. The Python command that writes IoT data into a file is __________.", answer: "write()" },
            { type: 'fill', q: "83. The step that comes last in the IoT data lifecycle is __________.", answer: "Visualization and Action" },
            // Tutorial 7
            { type: 'fill', q: "84. The “C” in the CIA security triad stands for __________.", answer: "Confidentiality" },
            { type: 'fill', q: "85. The protocol that adds TLS encryption to MQTT communication is __________.", answer: "MQTTS" },
            { type: 'fill', q: "86. A symmetrical encryption algorithm used in IoT is __________.", answer: "AES" },
            { type: 'fill', q: "87. The main purpose of firmware signing is __________.", answer: "To authenticate software origin" },
            { type: 'fill', q: "88. The Mirai botnet attack exploited __________.", answer: "Weak default passwords on IoT devices" },
            { type: 'fill', q: "89. The IoT security measure that ensures data is not altered during transmission is __________.", answer: "Integrity" },
            { type: 'fill', q: "90. TLS operates at the __________ layer of the OSI model.", answer: "Transport" },
            { type: 'fill', q: "91. Multi-factor authentication (MFA) requires __________.", answer: "Two or more verification factors" },
            { type: 'fill', q: "92. The IoT security principle that ensures users have only the permissions they need is __________.", answer: "Role-based access control (RBAC)" },
            { type: 'fill', q: "93. CoAPS is the secured version of the __________ protocol.", answer: "CoAP" },
            { type: 'fill', q: "94. The following is NOT a recommended IoT security practice: __________.", answer: "Open APIs without authentication" },
            { type: 'fill', q: "95. The acronym OWASP stands for __________.", answer: "Open Web Application Security Project" },
            { type: 'fill', q: "96. The cryptographic method that uses public and private keys is __________.", answer: "Asymmetric encryption" },
            { type: 'fill', q: "97. GDPR primarily protects __________.", answer: "Personal data of EU citizens" },
            { type: 'fill', q: "98. Data availability in IoT systems is ensured by __________.", answer: "Redundant systems and fail-over mechanisms" },
            // Tutorial 8
            { type: 'fill', q: "99. An example of an IoT application in agriculture is __________.", answer: "Soil moisture monitoring and automated irrigation" },
            { type: 'fill', q: "100. The component that acts as the edge device in a smart greenhouse system is __________.", answer: "Arduino with sensors" },
            { type: 'fill', q: "101. In an IoT system, the fog layer is typically represented by __________.", answer: "Raspberry Pi or Gateway" },
            { type: 'fill', q: "102. The cloud layer in IoT plays the role of __________.", answer: "Long-term data storage and analytics" },
            { type: 'fill', q: "103. The protocol commonly used for IoT data upload to cloud dashboards is __________.", answer: "MQTT" },
            { type: 'fill', q: "104. The free platform most often used for cloud-based IoT visualization is __________.", answer: "Thingspeak" },
            { type: 'fill', q: "105. In a smart home application, the device that usually controls lighting systems is __________.", answer: "Arduino microcontroller" },
            { type: 'fill', q: "106. The most important design step before starting an IoT project is __________.", answer: "Drawing the system architecture diagram" },
            { type: 'fill', q: "107. A key advantage of using fog computing in IoT is __________.", answer: "Reduced bandwidth and latency" },
            { type: 'fill', q: "108. A tool that can be used to visualize IoT data locally on Raspberry Pi is __________.", answer: "Matplotlib" },
            { type: 'fill', q: "109. In an IoT project, the component that handles decision logic or automation is __________.", answer: "Gateway/Fog node" },
            { type: 'fill', q: "110. The software design practice that improves IoT system scalability is __________.", answer: "Modular programming and reusable functions" },
            { type: 'fill', q: "111. The best way to protect IoT data during cloud upload is __________.", answer: "Use TLS encryption (HTTPS or MQTTS)" },
            { type: 'fill', q: "112. A key evaluation metric for IoT project performance is __________.", answer: "Response time and reliability" },
            { type: 'fill', q: "113. The document that summarizes an IoT project’s system design, data flow, and results is __________.", answer: "Project Report" }
        ]
    }
};
